### ISSUE TITLE
Use fixed compiler version.

### ISSUE THREAD

**Issue by kartik-giri** [blueprintsfi/core#3]
**Description:** All contracts and test file are using different compiler versions. Contracts should be deployed with the same compiler version that they have been tested thoroughly. 

**BlueprintManager.sol compiler version**
```javascript
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;
```

**Test file compiler version**
```javascript
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;
```

**Solution:**
Use fixed compiler version for example:
```javascript
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.24;
```
Please let me know if you want to fix this issue.

**Comment by kartik-giri** [comment]
Yes, it makes sense we should use most recent compiler version.

**Comment by kartik-giri** [comment]
"Solidity version should remain open imo. Would you agree?"

Yes, I believe it will let other devs to build more up on Blueprints. Without worrying about compiler version when they are integrating our contracts.

**Comment by Czar102** [comment]
Actually, I fixed the compiler version for the manager so that same compilation results were reproducible in development:
https://github.com/blueprintsfi/core/commit/06769a3831efd83b8125b2df989484937cca7355

**Comment by kartik-giri** [comment]
@Czar102 That's great.
