### ISSUE TITLE
Add Event Emission for Off-Chain Compatibility and ERCs Compliance

### ISSUE THREAD

**Issue by y0ng0p3** [blueprintsfi/core#4]
Hi @Czar102 !

I saw your message on Code4rena discord. I am interested in the role of Solidity developer and I would love to contribute to the project.

I have noticed that there is no event emission in the functions. I will start by adding it to the functions that need it. 
I have read your comments on the issue #1 opened by [DonGuillotine](https://github.com/DonGuillotine), so I will start with the BlueprintManager and its dependencies.  
I intend to finish this by Monday evening.

I would love to hear your comments on this.

**Comment by Czar102** [comment]
Hi @y0ng0p3! See the first sentence in the README of the repo:
> The core contract is the `BlueprintManager`. It has the functionality of an ERC6909, except is skimmed of events for gas consumption reasons.

If you think events should be emitted, I'm happy to hear arguments supporting this point of view. My current opinion is that they should remain removed.

**Comment by y0ng0p3** [comment]
I was thinking about third off-chain parties which may need updates of on-chain data. But, I believe I missed the statement you highlighted.
