### ISSUE TITLE
Solved BlueprintManager todo (L72-73)

### ISSUE THREAD

**Issue by y0ng0p3** [blueprintsfi/core#5]
I have split the if statement of transferFrom() into two if-else statements.  
From this :

```solidity
File: src/BlueprintManager.sol#L-66-L81

	function transferFrom(
		address sender,
		address receiver,
		uint256 id,
		uint256 amount
	) public virtual returns (bool) {
		// todo: check if actually two ifs are executed. Should check the sender
		// and potentially end the check before reading any state variables
		if (msg.sender != sender && !isOperator[sender][msg.sender]) {
			_decreaseApproval(sender, id, amount);
		}

		_transferFrom(sender, receiver, id, amount);

		return true;
	}
```

To this:

```solidity
File: src/BlueprintManager.sol#L-66-L88

	function transferFrom(
		address sender,
		address receiver,
		uint256 id,
		uint256 amount
	) public virtual returns (bool) {
		// The sender and its operators have infinite allowance
		if (msg.sender == sender) {
			_transferFrom(sender, receiver, id, amount);
			
			return true;
		} else if (isOperator[sender][msg.sender]) {
			_transferFrom(sender, receiver, id, amount);
			
			return true;
		} else {
			// Should decrease the caller allowance
			_decreaseApproval(sender, id, amount);
			_transferFrom(sender, receiver, id, amount);
			
			return true;
		}
	}
```

I have also written a test linked to the function.

**Comment by kartik-giri** [comment]
Hi @y0ng0p3, I hope you're doing well! I just wanted raise my concern about yours `transferFrom` function implementation. Don't you think it will cost more gas compared to the previous one?

**Comment by y0ng0p3** [comment]
Hi @kartik-giri , thank you for the feedback. 

In fact I thought about and wrote two tests, one calling the current implementation of the transferFrom function and the other calling the version I wrote. The latter used less gas than the formee by around 80 if I remember well (I did not keep the report). Someone might say it is not much, yet there is a positive gas consumption difference.

**Comment by kartik-giri** [comment]
@y0ng0p3 That's great can you please share me the test file which you have written. It would be great help for me to test at my end.

**Comment by kartik-giri** [comment]
@y0ng0p3 Yea sure, enjoy your time :)

**Comment by Czar102** [comment]
I'll get back on the test soon :tm:

**Comment by Czar102** [comment]
What was meant by the todo comment is that the code:
```js
if (msg.sender != sender && !isOperator[sender][msg.sender]) {
	_decreaseApproval(sender, id, amount);
}
```

should evaluate to an equivalent of:
```js
if (msg.sender != sender) {
	if (!isOperator[sender][msg.sender])
		_decreaseApproval(sender, id, amount);
}
```

So, that the `isOperator` mapping is not accessed whenever `msg.sender == sender` – that's a scenario where we know it doesn't make sense to check it. Solidity should do it by default…

When I implemented a `transferFrom` test, the change seemed to optimize the code slightly, but some other functions are considered way more expensive:
```
$ forge snapshot --diff
...
test_transfer(address,address,uint256) (gas: 1 (0.002%)) 
test_basket(address,uint256,uint256) (gas: 56 (0.025%)) 
test_transferFrom(address,address,uint256,bool,bool) (gas: -22 (-0.036%)) 
test_vesting(address,uint256,uint256,uint256,bool) (gas: 17251 (2.566%)) 
Overall gas change: 17286 (1.194%)
```

Very odd that such a large impact was there. But 22 gas saving is too little for me to consider this a "slot reading saving", so I think for now we should leave the code as is, more readable?

See the commit adding the test and removing the todo: https://github.com/blueprintsfi/core/commit/78e749505d923a2bfeb227c656153d10b61056d8

Do you think it's a reasonable solution?

**Comment by y0ng0p3** [comment]
@Czar102 thank you for the feedback and clarification. 
Indeed, the current implementation is more readable. Also, since the optimization has not so much, I agree we should keep transferFrom as it.

**Comment by kartik-giri** [comment]
Hi @y0ng0p3 I appreciate your work brother. Thanks for making us think, from many different perspectives.

**Comment by y0ng0p3** [comment]
Thanks to you. For your comments and feedback. For sure, I'll continue diving into the project.
